### ISSUE TITLE
Having error on startup

### ISSUE THREAD

**Issue by tommyd75** [codetwice/homebridge-http-securitysystem#1]
Hello, trying to implement your plugin with my Homeseer2 server which has a json api but I keep getting this error, maybe my formatting is wrong?

[7/28/2016, 5:08:20 PM] Loading 12 accessories...
[7/28/2016, 5:08:20 PM] [Home security] Initializing Http-SecuritySystem accessory...
/usr/local/lib/node_modules/homebridge-http-securitysystem/index.js:32
            url: config.urls.read.url,
                                 ^

TypeError: Cannot read property 'url' of undefined
    at Object.HttpSecuritySystemAccessory (/usr/local/lib/node_modules/homebridge-http-securitysystem/index.js:32:25)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:244:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

 **This is what I'm using in the config file**

{
            "accessory": "Http-SecuritySystem",
            "name": "Home security",
                        "http_method": "GET",
            "urls": {
                "stay": { "url": "http://192.168.1.100/home%20stay" },
                "away": { "url": "http://192.168.1.100/home%20away" },
                "night": { "url": "http://192.168.1.100/home%20night" },
                "disarm": { "url": "http://192.168.1.100/home%20off" },
                "readCurrentState": { "url": "http://192.168.1.100/jsonapi.asp?action=getdevice&id=z99", "body": "" },
                "readTargetState": { "url": "http://192.168.1.100/jsonapi.asp?action=getdevice&id=z99", "body": "" }

}

 ***\* I was able to do this with an older legacy plugin that i set up as a lock, and that worked fine, but I was wondering if maybe the spot that has it check the body might be wrong in my case it was checking a specific part "value" when I navigate to that webpage it shows the below output, I tried changing it to value instead of body but I think I need to tell it to parse the body just for the "value" ****

{"id": "99", "name": "99 Virtual HomeKit Status", "room": "VISTA ZONES", "floor": "", "dimmable": false, "status": 17, "value": 0, "since": "7/28/2016 4:49:29 PM", "type": "Status Only", "status_support": false, "misc": "16"}

 **Also I have included below a snipet of the code from the old lock type accessory I was using.**

request('http://192.168.1.100/jsonapi.asp?action=getdevice&id=99', function (error, resp, body) {
      if (!error) {
        var response = JSON.parse(body);
        var value = response['value'];
        callback(null,value);
      }
      else {
        callback(error);

**Comment by codetwice** [comment]
Hey, 
It looks like the documentation of the plugin is a bit off as it is trying to read both the current and target state from the config setting for "read". Can you please try the following config and see if it works? If it does I'll update the docs. 

```
{
	"accessory": "Http-SecuritySystem",
	"name": "Home security",
	"http_method": "GET",
	"urls": {
	"stay": { "url": "http://192.168.1.100/home%20stay" },
	"away": { "url": "http://10.10.10.120:81/home%20away" },
	"night": { "url": "http://192.168.1.100/home%20night" },
	"disarm": { "url": "http://192.168.1.100/home%20off" },
	"read": { "url": "http://192.168.1.100/jsonapi.asp?action=getdevice&id=z99", "body": "" }
}
```

**Comment by tommyd75** [comment]
OK, the above works perfectly except for the status once I've armed or disarmed, it just keeps showing "disarming" or "arming" but never changes, I have to close the app out and then reopen it then it updates correctly.

**Comment by nightfreak** [comment]
same for me, when opening the app, the status is shown correctly.
But when I change the status, my security system gets the command and then the homekit app stays showing "activating" and never gets the new status.

is there a fix for this?

**Comment by codetwice** [comment]
When I created this plugin with an iPhone app called MyTouch Home, I noticed that it never bothered rereading the state after issuing a state change command, this is why the reading the current state and the target state is not implemented properly. 
I will have to take a new look at it now that Apple released a proper HomeKit app as part of iOS.

**Comment by nitaybz** [comment]
Solved in the my forked version:
https://github.com/nitaybz/homebridge-http-securitysystem.git

hope it will be merged.
