### ISSUE TITLE
Help with XML output

### ISSUE THREAD

**Issue by stich86** [codetwice/homebridge-http-securitysystem#11]
Hi 
i want to integrate this plugin to my alarm but the output is in XML and not normal HTTP body.
For arm\disarm I think it's not a problem because I'll pass in the HTTP url command to enable\disable alarm, but the status it's problematic. Currently it's outputted in XML like this:

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<partitionsStatus>
    <partition>ARMED</partition>
    <partition>ARMED</partition>
    <partition>ARMED_IMMEDIATE</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
    <partition>DISARMED</partition>
</partitionsStatus>
```

in my case I've three partition, but usually both are armed (in away and night mode) 

Thanks for any help!

**Comment by codetwice** [comment]
Hm, so to me it seems like you have a single block of response but in HomeKit you would want to have 3 different security devices, right? One for each of your partitions?

**Comment by stich86** [comment]
i can have just the first one, because when alarm is armed, the first partition is always enabled
i'm trying to implement on your plugin the xml\xpath to parse this XML, but it's not so easy

**Comment by codetwice** [comment]
Well that's what I was also thinking about. There were already requests for some sort of response to status mapping in my homebridge plugin, your problem is a very special version of that. 
I suppose what needs to be done here is 2 mappings chained:

1. First an XPath query to retrieve the correct partition
2. Followed by a static mapping of ARMED to the correct HomeKit security identifier

And as far as I can tell these mappings need to be set up by configuration because you may want one config for one of your partitions and another config for another partition, using the very same lib. 
I will see what I can do for you.

**Comment by stich86** [comment]
ok i made some progress, but i receive 401 from my alarm.. it need basic auth, is this plugin using it?

**Comment by codetwice** [comment]
No, that's another request I have in the backlog :(
If you check one of the previous issues here on GitHub you'll see someone posting how to modify the plugin to do basic auth. 
Let me know if you make progress, I'd like to improve the securitysystem further as there seems to be increasing demand for it.

**Comment by stich86** [comment]
ok' i've added basic auth and xpath check, this is current my mod.. i know it's not elegant but can suite my needs

`        getState: function(url, body, callback) {
                if (!url) {
                        callback(null);
                }

                this.httpRequest(url, body, function(error, response, responseBody) {
                        if (error) {
                                this.log('GetState function failed: %s', error.message);
                                callback(error);
                        } else {
                                var xmlstate = parseInt(responseBody);
                                var doc = new dom().parseFromString(responseBody)
                                var part1 = xpath.select("string(//partition[1])", doc)
                                var part2 = xpath.select("string(//partition[2])", doc)
                                var part3 = xpath.select("string(//partition[3])", doc)
                                var mapObj = {ARMED:1,ARMED_IMMEDIATE:1,DISARMED:0};
                                var re = new RegExp(Object.keys(mapObj).join("|"),"gi");
                                var state_p1 = parseInt(part1.replace(re, function(matched){return mapObj[matched];}));
                                var state_p2 = parseInt(part2.replace(re, function(matched){return mapObj[matched];}));
                                var state_p3 = parseInt(part3.replace(re, function(matched){return mapObj[matched];}));

                                if (state_p1 == 1 && state_p2 == 0 && state_p3 == 1) {
                                        var state = 2
                                        this.log("State is currently %s", state);
                                        callback(null, state);
                                } else if (state_p1 == 1 && state_p2 == 1 && state_p3 == 1) {
                                        var state = 1
                                        this.log("State is currently %s", state);
                                        callback(null, state);
                                } else {
                                        var state = 3
                                        this.log("State is currently %s", state);
                                        callback(null, state);
                                }
                        }
`
i've also modify this piece of code to avoid spinning circle when change status

`getServices: function() {
		this.securityService = new Service.SecuritySystem(this.name);

		this.securityService
			.getCharacteristic(Characteristic.SecuritySystemCurrentState)
			.on('get', this.getCurrentState.bind(this));

		this.securityService
			.getCharacteristic(Characteristic.SecuritySystemTargetState)
			.on('get', this.getTargetState.bind(this))
			.on('set', this.setTargetState.bind(this));

		return [this.securityService];
	}
};`

if you have any suggestion.. may be to make partition configurabile it's appreciated.. i'm not an expert of nodeJS.. but I like to learn new things :)

**Comment by codetwice** [comment]
Thanks! I'll create configuration that allows something like this. Out of curiosity, why wasn't it enough to check only state_p2 for its value?

**Comment by stich86** [comment]
Yes it could be a better solution
As I said I'm not an expert ^_^"
I play with your code yesterday before my holiday 
After come back I want to add other parameters like PIN and Scene ID to use with Ksenia Alarms.

If you agree I can make a fork and adjust for Lares Alarms

Thanks!

**Comment by codetwice** [comment]
So I tried and came up with a better solution, I just hope it's good enough for you. I implemented response mapping in a configurable and chainable way. I implemented 3 different mappers:
- An XPath mapper, which can be used to extract strings from an XML
- Static mapper, which maps static strings to static strings (can be used to map your ARMED to 2)
- Regexp mapper, which you don't really need

The change is only up on the develop branch, pull that one if you want to test it. 
In your case I'd try something like this:

```
"mappers": [
    {
        "type": "xpath",
        "parameters": {
            "xpath": "//partition[3]/text()"
        }
    },
    {
        "type": "static",
        "parameters": {
            "mapping": {
                "ARMED": "2",
                "ARMED_IMMEDIATE": "1"
                "DISARMED": "3"
            }
        }
    }
]
```

This may not be sufficient for you as you had some weird logic with your if conditions regarding the 3 partitions. I don't know if you can map it down to reading a single value out of the response :(

**Comment by stich86** [comment]
The problem is that I need to check at least two partition to know if the alarm is in away or night mode, because the web server is implemented in this way (and there is no other possibility).

I will try this branch. Do you thing that's possible to add At least PIN in your module?

Thanks!

**Comment by codetwice** [comment]
I do not understand really know about PINs and SceneIDs. Are they something specific to your alarm system? What are they for? 
I checked the homekit characteristics and it doesn't seem to have anything related to PINs...

**Comment by stich86** [comment]
My Alarm need to pass (after http with) a PIN into the GET request do execute scene command. scene command is essential an ID that instruct alarm to arm/disarm various partition. This system doesn't expose a public API so I've simulated the same action done by the GUI

**Comment by codetwice** [comment]
You can add GET parameters to the URLs in the config easily, just use URLs like:

http://your-security-device/some-api-endpoint/action?pin=1234&sceneID=1234

Or do you have to do multiple calls?

**Comment by stich86** [comment]
Yes I know
I currently use this method. I've checked your Devel branch and I have some question regarding xpath patterns. In the cose I see there is a foreach, can I put multiple patterns? I've checked again the mobile apps and it seems to provide the current scene status (instead of partition).m, I need to do a network trace to get the specify URL to call

**Comment by codetwice** [comment]
Right now the XPath mapper only selects a single value from the XPath. There are some XPath functions you can use to fake multiselection, like concat. I just updated develop to another version of the same parser which works better with such functions. 
You may try XPaths like 

`"xpath": "concat(//partition[1]/text(), '_', //partition[2]/text())"`

Not very elegant but maybe this plus a static mapper can do the trick.

**Comment by stich86** [comment]
i've found hidden XML status page to get (in text) the current ARM mode in this output:

`<vkStatus>
<generic>2</generic>
<arm_mode>Night Mode</arm_mode>
</vkStatus>`

i'll try to test your devel version using this new mapping instead check all partitions and I let you know :)

**Comment by stich86** [comment]
Hi code,

I've tested the Devel version and works like a charm!
Mapping the "arm_mode" to my three scenarios and report to HomeKit as expected. Thanks also to integration of polling I receive notification on my watch when alarm is armed/disarmed.

Great work!! Thank you so much 😊
