### ISSUE TITLE
How to trigger the alarm.....

### ISSUE THREAD

**Issue by roe1974** [codetwice/homebridge-http-securitysystem#12]
Hi.....
Is it possible to trigger the Alarm on (State:4) with a curl http event ?

Richard

**Comment by codetwice** [comment]
Nope, you cannot directly connect to this securitysystem and change its state, it is reaching out to a set of URLs and reads the state from there. 

What you can do is that you create an HTTP service which stores the state (including state 4), which has nothing to do with Homebridge, it's just a regular HTTP app (it can be a PHP script or full app or some special solution just for this purpose). This Homebridge service can be then configured to query this HTTP service of yours for the state and that way you can communicate a state 4 to my plugin. 

As you have control of this state provider HTTP service, you can decide yourself HOW you want to have its state changes. It could be a curl call as well. 

I personally use NodeRed for this, there you can define HTTP endpoints, connect them to various logic components, craft responses. I have endpoints which are used by the security system for querying the state and I have other HTTP endpoints which I can call to set the state and trigger alarms.
