### ISSUE TITLE
Help with XML response

### ISSUE THREAD

**Issue by mach1009** [codetwice/homebridge-http-securitysystem#14]
Setting the state does work well. Great work!

How can i get the state from this XML? „value“ is the state. 

<?xml version="1.0" encoding="ISO-8859-1" ?><state><datapoint ise_id='52967' value='4'/></state>

Thanks for your help.

**Comment by codetwice** [comment]
I think you forgot to attach the XML.

**Comment by mach1009** [comment]
Sorry

<?xml version="1.0" encoding="ISO-8859-1" ?><state><datapoint ise_id='52967' value='4'/></state>

**Comment by mach1009** [comment]
?xml version="1.0" encoding="ISO-8859-1" ?><state><datapoint ise_id='52967' value='4'/></state

**Comment by mach1009** [comment]
`<?xml version="1.0" encoding="ISO-8859-1" ?><state><datapoint ise_id='52967' value='4'/></state>`

**Comment by codetwice** [comment]
Try it with a mappers sections like this:

```
"mappers": [
  {
    "type": "xpath",
    "parameters": {
      "xpath": "string(/state/datapoint/@value)"
    }
  }
]
```

**Comment by mach1009** [comment]
It works. Thanks
