### ISSUE TITLE
Plugin as Garagedoor

### ISSUE THREAD

**Issue by mach1009** [codetwice/homebridge-http-securitysystem#15]
@codetwice do you think ist is easy to Build an equal Plugin for a garagedoor?

**Comment by codetwice** [comment]
Yes, I suppose it wouldn't be very difficult to duplicate this and modify it a little bit. The SecuritySystem has 2 main characteristics

- SecuritySystemCurrentState (read-only) 
- SecuritySystemTargetState (read-write)

while the GarageDoorOpener has 3: 

- CurrentDoorState (read-only)
- TargetDoorState (read-write)
- ObstructionDetected (read-only)

Even a search-and-replace would almost get the job done. There would be 4 URLs to specify

- read current state (5 possible values returned)
- read the target state (2 possible values returned)
- set the target state (2 possible values)
- read the obstruction state (2 possible values returned)

**Comment by mach1009** [comment]
Thank you for your reply. I will try it. 👍🏻
