### ISSUE TITLE
Little bug in Line 261 of index.js

### ISSUE THREAD

**Issue by mach1009** [codetwice/homebridge-http-securitysystem#17]
I think there is a bug in line 261 of index.js
It is not possible to set the SecuritySystemCurrentState. You only can get it.

Line 261 is:
`self.securityService.setCharacteristic(Characteristic.SecuritySystemCurrentState, state);`

I think it has to be:
`self.securityService.getCharacteristic(Characteristic.SecuritySystemCurrentState);`

Im working on changing the plugin as garagedoor. Only with this change it works correctly.

**Comment by codetwice** [comment]
Thanks for pointing this out, I fixed the issue in this project as well. After some testing I came to the conclusion that that line was not needed at all, I recommend that you test your garage door plugin with the line completely removed, maybe it also works like that.

**Comment by mach1009** [comment]
Thanks for your reply. You are right. It is also working without this line. 
At the moment i‘m testing the garage door opener. When it works correctly, i will publish ist. But I get stuck on refreshing the state in the Homeapp while the app is open. Now i noticed it is the same with the scurity system.
Example: Current state and target state are „Off“ when you open the app. If the state is changed by the device (not by the app) to „At home“, while the app is open, the app shows „disarming“ until you refresh by closing/opening or changing the room.
I think that happens, because the target state is not corrctly refreshed by the polling. I tried a lot of changes, also poll the target state too. But i did not solve this till now. Probably you have an idea?

Best regards

**Comment by codetwice** [comment]
I checked and I can confirm that polling doesn't seem to work properly while the app is open... If you use 2 Apple devices with the Home app open and one sets the status, it is reflected by the other device immediately, but not if the state is set by a non-HomeKit device.

I'll have to investigate this further.

**Comment by mach1009** [comment]
For the garage door, i solved it in this way:
`		emitter.on("longpoll", function (state) {
			self.log("Polling noticed status change to %s, notifying devices", state);
			if (state == 2) {
				self.garagedoorService
				.getCharacteristic(Characteristic.TargetDoorState)
				.setValue(0);
				}
			else if (state == 3) {
				self.garagedoorService
				.getCharacteristic(Characteristic.TargetDoorState)
				.setValue(1);
				}
			self.garagedoorService
				.getCharacteristic(Characteristic.CurrentDoorState)
				.setValue(state);
		});`

**Comment by mach1009** [comment]
Sorry. Last question. You have attached the Apache license. In the package.json you write BSD-2-Clause. Why the difference?
Thank you for your help!

**Comment by codetwice** [comment]
Hello, thanks for the tip with the polling. I also adjusted my code there. Instead of your guess-the-target-state-based-on-the-current-state solution I decided to simple poll both the target and the current state. That did the trick, too. 

About your question regarding the license, it was an oversight from my side. BSD-2 is the correct license, there should be a new LICENSE file up in the project.

**Comment by mach1009** [comment]
Hi!
That is fine. I will stay at my solution, because i have to minimise the polling events. When i finished my little project, i will have 3 variants of your plugin working on my homeautomation system (security, garage and window). 

Good work!
