### ISSUE TITLE
Basic HTTP authentication (Fibaro HC2)

### ISSUE THREAD

**Issue by 10der** [codetwice/homebridge-http-securitysystem#2]
please add to support Fibaro HC2 with Basic HTTP authentication 

`headers: { 'Authorization': 'Basic ' + new Buffer(username + ':' + passw).toString('base64') }`
see also: https://dzone.com/articles/nodejs-call-https-basic

**Comment by codetwice** [comment]
Hey, thank you, I added it to the code, it's already on the master branch. When auth.username and auth.password are specified in the config, the plugin not only sends them inside the Auth header of the request but also in form of such an Authorization header.
