### ISSUE TITLE
No hint in case of tripped alarm

### ISSUE THREAD

**Issue by Erokani** [codetwice/homebridge-http-securitysystem#21]
Hi,

I used your plugin to connect to a Zipato alarm. I did some rules and succeeded for activation and deactivation states (set & read, for home away & night mode).

However, I could identify that when my Zipato alarm is tripped, then the plugin is not identifying it. And therefore I miss one key point :)

In homebridge logs e.g. I could not see any mapper applied for 4...
In Zipato side however I can well see the related virtual meter sensor set to 4.

I have on doubt: could you advise if your plugin is looking the tripped state/value on the readCurrentState url, or readTargetState url?

Thank you in advance

**Comment by codetwice** [comment]
Hi, 
the triggered state is handled the very same way as any other state: the regular 10 second polling reads the current state (which can be stay, home, night, disarm and triggered) and the new state differs from the old one, it notifies your devices. I did some testing on the master branch, for me it seems to be working fine. When the readCurrentState returned 3, then 4, then my iPhone was notifying me about the triggered alarm. 

My test case was the following:
1) I created a text file on a webserver with the content of "3"
2) I set my homebridge's readCurrentState to the URL of this text file, no mappings whatsoever
3) Restarted homebridged
4) Noticed that my iphone's home app reported the alarm to be off
![image](https://user-images.githubusercontent.com/7754243/41959759-31454434-79ee-11e8-81a8-2d597083d9a0.png)
5)  edited the text file, change the number from 3 to 4
6) Less than 10 seconds later my iPhone notified me about the trigger and the Home app also reflected the new state. 
![image](https://user-images.githubusercontent.com/7754243/41959762-34547e4c-79ee-11e8-9a5c-b21b487b7c6d.png)

So, are you sure that your system is properly reporting status 4 to the plugin? Can you test it with a plain text file as well? For your convenience, I left my test files intact, you can use these ones as well:
- http://dev.cloudy.dyndns.org/homebridge/arm.json (returns 1)
- http://dev.cloudy.dyndns.org/homebridge/disarm.json (returns 3)
- http://dev.cloudy.dyndns.org/homebridge/trigger.json (returns 4)

**Comment by brownad** [comment]
@Erokani did you solve this? I have the same setup but found a way out.

Zipato is a pain to deal with, I assume you setup a myriad of virtual switches / sensor (meters) etc. to deal with incoming requests from Homebridge and to hopefully push events out from Zipato to your sensors, almost like a mirror of your alarm system but with addressable endpoints?  Well if you run a simple PHP server somewhere then you can send the status events to a URL, write that to a file e.g. json, and then have this nice plugin poll it constantly (0,1,2,3,4).  That should be it, if only Zipato provided a simple way to GET values without the nasty auth procedure.

Now one question, I've wired this up, but in a problem.  I have all the events from Zipatile pushing to my PHP server correctly, updating the status of the plugin correctly, but from the app (home) I cannot drive status changes which call the remote API, what's the deal there?  All my endpoints work (simple setters, nothing else), how did you get that working correctly?

**Comment by Erokani** [comment]
Hi,

Sorry, you’re right, I should have come back here to advise on the way out... 

@codetwice, thanks for your tests an helpful advise!
As you suggested, the mistake was on my zipabox server side, not on your homebridge plugin.

@brownad, my issue was that my rules on zipato server side were not correct and not setting the appropriate attribue to 4 (thus no event could be detected on homebridge side ;)).

I have a quite « simple » set-up: one virtual meter on my zipabox, which therefore can be read and set via html call (if I recall I made a post one day on zipato forum. Otherwise you’ll find plenty of others. Don’t know if applicable to Zipatile). 2 attributes on this virtual meter: one for current state, one for target state. Then some rules on the zipabox to update them based on zipabox security status and others for the opposite, to update zipabox security status based on them.

Note: I do have a kind of php proxy set-up between other homebridge plugins and my zipabox (for hard-wired movement sensors and z-wave doors sensors e.g.)

For stay, away, night, disarm url, I must have url allowing you to change your zipatile status. I guess this is what you’re missing. Check virtual meter url how-to on zipato forum. A bit tricky but works with a good reliability. 

Hope this helps

**Comment by Erokani** [comment]
Example of virtual meter set-up: 
https://community.zipato.com/knowledge-base/article/virtual-thermometer-adding-setting-the-temperature

**Comment by brownad** [comment]
Cool

So are you able to read the status directly from the plugin to zipatile or just push requests to it - I’m guessing you use the remote API here? But yeah I have the HTTP from zipatile working correctly to update the status, am happy with that, just can’t get the plugin to drive the zipatile status eg HOME, AWAY etc - the app sits in Arming state.. I noticed you had an issue initially how did you set this up to work from the plugin to the zipatile?  Again I have the virtual endpoints polished and the work with the GET request from a browser performing the right status.

Thanks

**Comment by Erokani** [comment]
Well... hem... sorry again... 

I was checking my real homebridge config (vs what I documented I did in my admin guide, which I missed to update  :s) and was about to bring you a more accurate & helpful update...

So, disregard above: for some obscure reasons, virtual meter trick (which I used previously to plug Netatmo weather station within Zipabox) is not anymore what I’m using (I guess I got skeptical with Zipato reliability...). So I finally went through a php script to log into Zipabox API as workaround, as you mentioned... I just forgot I did ^_^ (was months ago)

Anyway, so, my general plumbery set-up is a bit like this (thanks Zipato.................): 

Zipato virtual alarm <=> Zipato virtual meter (2 attributes) + 1 virtual switch <=> php script <=> homebridge security plugin <=> HomeKit

PS: my Zipato virtual alarm is based on hard-wired mouvement sensors and z-wave door/window sensors.

My homebridge config look like this:

"urls": {
   "stay": { "url": "http://192.168.0.1/statusalarme.php?type=set&value=0", "body": "" },
   "away": { "url": "http://192.168.0.1/statusalarme.php?type=set&value=1", "body": "" },
   "night": { "url": "http://192.168.0.1/statusalarme.php?type=set&value=2", "body": "" },
   "disarm": { "url": "http://192.168.0.1/statusalarme.php?type=set&value=3", "body": "" },
   "readCurrentState": { "url": "http://192.168.0.1/statusalarme.php?type=current", "body": "" },
   "readTargetState": { "url": "http://192.168.0.1/statusalarme.php?type=target", "body": "" }
},

Where 192.168.0.1 is my php server plugging into Zipabox API, so that I can read the current & target state (the 2 attributes of my ZIpato virtual meter mentioned above), but also **modify** them.

My php script is based on what can be found in zipato forum. It is well not well re-written by myself and so dirty that it is not worth sharing, trust me (^_^). It just does the job...
See here for the script to be adapted to your needs: https://community.zipato.com/topic/local-mode-api-

Yes it induces some vulnerabilities from a security standpoint... But I have a few mitigations in place (what is the device requesting the changes e.g.), and an attacker would already need to have penetrated my home network, reverse engineering the data flows, etc... so low risk at the end compared to the target our place would represent ;)

The virtual switch is again a workaround for unreliable Zipato things... It is set as siren within the alarm. It is needed in case alarm is triggered for the required set to « 4 » which was missing, because of zipato bug....

On Zipato side, as summary:
- 1 virtual meter, with 2 attributes: current state & target state
- 1 virtual switch set as siren of the virtual alarm
- 2 rules to update these virtual meter attributes based on Zipato virtual alarm changes. See screenshot of related rules
- 2 rules to update Zipato virtual alarm based on the virtual meter attributes. See screenshot of related rules
- 1 rule to transform the virtual switch as stateless switch

Hope this helps better :)
![e4b57325-c72a-4ce9-8dc5-82d380e018d7](https://user-images.githubusercontent.com/22945461/44883323-93472380-acae-11e8-88f0-963b4e6c6f0c.png)
![b38f6927-9c1f-4f24-88b6-c0a387f90e36](https://user-images.githubusercontent.com/22945461/44883325-93dfba00-acae-11e8-9c21-b8907ff2f80c.png)
![b259b2af-31df-458f-995b-3d292dc18f33](https://user-images.githubusercontent.com/22945461/44883327-93dfba00-acae-11e8-8ef4-fd07f01ee3a3.png)
![d9d386ed-79b4-44af-9a34-48560982bec8](https://user-images.githubusercontent.com/22945461/44883330-97734100-acae-11e8-8fbb-4fc8b27169d7.png)

**Comment by brownad** [comment]
Very cool and superb explanation of your setup, sorted my problem now targetState and currentState was the issue, and yeah working against Zipato is far from fun, if they added HomeKit support it might be nice to use.  I wouldn't trust house security with it, nothing more than a shiny panel on the wall for me.  

Think @codetwice can close this one 👍
