### ISSUE TITLE
Explicit Parameter for Arming

### ISSUE THREAD

**Issue by lockpicker** [codetwice/homebridge-http-securitysystem#22]
I've looked around and can't find anything to guide me here so thought I'd ask.

My security system has an arming delay of 60 seconds so essentially from the moment I arm that system, I have 60 seconds to get out of the house. 
This essentially means that after triggering the arming url, the system is in the "arming" state but not in any of the explicit states of away, night, disarmed etc. 
Question is what value should I return through the read current state API call when this is the case?
Also, this is the same when arming in night mode or away mode

**Comment by codetwice** [comment]
If your response does not contain any hints about it being armed for day or night, there is not much you can do there but if you have a custom API layer in between that should totally do the trick. Just create 2 HTTP endpoints on your API layer on the URLs specified by getCurrentState and getTargetState. When these points are being hit by homebridge, just have your API 

1) read the actual response of your security system (which, I guess, is either a state or a timer). 
2) if it is an already active state, have both getTargetState and getCurrentState translate it to its equivalent value in HomeKit (0-4)
3) if it is timer, have getCurrentState transform it into 3 (disarmed) and have getTargetState transform it into some sort of armed state (0, 1 or 2). 

If you can't tell from the timer what sort of armed state it is going to be, you can just take one arbitrarily, like 1 for away armed. The worst thing that can happen is that during the arming mode your phone will report the wrong target but after it's armed it will already show it properly.

**Comment by lockpicker** [comment]
Thanks! That sounds like it should work. Will write that layer and report back.

**Comment by codetwice** [comment]
I added support for custom HTTP headers in version 1.0.5. You should be able to use it for setting the Content-Type to whatever you need.

**Comment by lockpicker** [comment]
Thanks @codetwice!
