### ISSUE TITLE
GetState function failure causes homebridge to crash

### ISSUE THREAD

**Issue by lockpicker** [codetwice/homebridge-http-securitysystem#24]
So, due a series of unfortunate events, my alarm went off in the middle of the night and woke us up. 
So naturally now that I was awake, I had the insatiable urge to debug this in the middle of the night and I traced the origin of the series of events to this:

I noticed that when homebridge-http-securitysystem calls GetState and the GetState fails for any reason (in my case for some reason the dns lookup failed temporarily, which can happen due to many reasons including network congestion etc), this results in the error being thrown back to the homebridge events.js which then throws an exception and crashes homebridge. 

I think we should have a more graceful way of handling and ignoring / retrying on something like this which should be non-fatal error. 

Log below: 

[2018-10-9 13:55:16] [Home security] GetState function failed: getaddrinfo EAI_AGAIN myalarmproject-21078.cloudfunctions.net:443
[2018-10-9 13:55:16] [Home security] Current state changed to undefined
						events.js:136
						      throw er; // Unhandled 'error' event
						      ^
						Error: getaddrinfo EAI_AGAIN myalarmproject-21078.cloudfunctions.net:443
						    at Object._errnoException (util.js:1031:13)
						    at errnoException (dns.js:60:15)
						    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)

------------

After the above error, homebridge crashes.

Any ideas?

**Comment by codetwice** [comment]
Good catch. I know the problem but in my case it wasn't my own plugin crashing Homebridge but the Philips Hue bridge, because of the same reason... Really annoying. I will add some sort of error handling for this situation.

**Comment by codetwice** [comment]
This issue should be fixed on the master branch. Pull the latest version (I also pushed it to npmjs, v1.0.5). 

The root of the problem was that the polling-to-event library I was using had some inconsistency in its documentation regarding which event to subscribe to in order to catch the errors and my plugin was listening to the wrong one.

**Comment by lockpicker** [comment]
Fantastic. Thanks, appreciate the fix. 

Ironically the bug will fix itself in my case :) The next time Homebridge crashes, it will restart the docker container it’s running in and on restart, it will auto update the plugin :)

And I’ll thank you in advance, as once I’ve tested thoroughly, i’ll release the plugin for Honeywell Tuxedo alarm panels for general consumption which is now based on your awesome work.
Cheers!
