### ISSUE TITLE
Realtime Notifications

### ISSUE THREAD

**Issue by stbluesrul** [codetwice/homebridge-http-securitysystem#7]
Is it possible to get realtime polling added?  Right now, homekit will only notify you if the alarm was triggered if you open the app or check in control center.  Homebridge-http is able to do this, it requests device status once a second.

https://github.com/rudders/homebridge-http

**Comment by codetwice** [comment]
Sorry for the late response. I looked into what was being done there and did some testing and concluded that this was a Good Thing so I also added realtime support to this plugin. Get the develop branch to try it, I will merge it to master if it works out alright.

**Comment by stbluesrul** [comment]
Just tested the dev branch and it works great!  Thank you for adding realtime support!

**Comment by codetwice** [comment]
I'll merge it into master then.
