### ISSUE TITLE
expected response body

### ISSUE THREAD

**Issue by perote2000** [codetwice/homebridge-http-securitysystem#9]
HEllo, I did not figureout what is the http body this plugin is expecting...

is something like
HTTP/1.1 200 OK<body><html>1</html></body>

Or is expecting to change 200 stats? like...
HTTP/1.1 0 OK<body><html></html></body> (for STAY)
HTTP/1.1 1 OK<body><html></html></body> (for AWAY)

Thanks a lot

**Comment by codetwice** [comment]
You will need a proper HTTP response for this. The current status is expected in the body of the response, not in the headers. I am using this module with Node-Red with this, here is a sample of a response it sends:

```
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Length: 1
Content-Type: text/html; charset=utf-8
ETag: W/"1-z80ghJXVZe9m59/5+Ydk2g"
Date: Wed, 02 Aug 2017 08:58:14 GMT
Connection: keep-alive

1
```

I think you can omit most (maybe all) of the headers  so in theory even a response like this could work: 

```
HTTP/1.1 200 OK

0
```

**Comment by perote2000** [comment]
Thanks. Ive tested that way... Ill check what I did wrong way...

Enviado desde mi iPhone

**Comment by codetwice** [comment]
Closed due to inactivity.
